import pptxgen from "pptxgenjs";
import type { DocumentChatMessage, ParsedDocument } from "../documentTypes";

const BLUE = "2563EB";
const DARK = "0F172A";
const MUTED = "64748B";
const LIGHT_BLUE = "EFF6FF";
const LIGHT_GRAY = "F8FAFC";
const SLIDE_W = 13.333;
const SLIDE_H = 7.5;
const MARGIN_X = 0.65;

type PptxDocument = InstanceType<typeof pptxgen>;
type PptxSlide = ReturnType<PptxDocument["addSlide"]>;

export async function buildDocumentPptxExport(document: ParsedDocument): Promise<Buffer> {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "DocuMuse";
  pptx.company = "DocuMuse";
  pptx.subject = "DocuMuse document analysis export";
  pptx.title = safeText(document.title || document.filename || "DocuMuse Export");
  pptx.theme = {
    headFontFace: "Arial",
    bodyFontFace: "Arial"
  };

  addTitleSlide(pptx, document);
  addSummarySlide(pptx, document);
  addKeyPointsSlide(pptx, document);
  addKeywordsSlide(pptx, document);
  addSectionSlides(pptx, document);
  addPptOutlineSlides(pptx, document);
  addCreativeSlide(pptx, document);
  addChatSlides(pptx, document);
  addClosingSlide(pptx);

  const output = await pptx.write({ outputType: "nodebuffer", compression: true });
  return Buffer.isBuffer(output) ? output : Buffer.from(output as ArrayBuffer);
}

function addTitleSlide(pptx: PptxDocument, document: ParsedDocument) {
  const slide = newSlide(pptx);
  slide.addText("DocuMuse", { x: MARGIN_X, y: 0.5, w: 2.4, h: 0.35, fontSize: 15, bold: true, color: BLUE });
  slide.addText(truncateText(document.title || document.filename, 110), { x: MARGIN_X, y: 1.35, w: 10.8, h: 1.15, fontSize: 30, bold: true, color: DARK, breakLine: false, fit: "shrink" });
  slide.addText(
    [
      `Filename: ${document.filename}`,
      `Exported at: ${new Date().toLocaleString("zh-CN")}`,
      `Provider: ${document.analysisProvider || "Not generated"}`,
      `Model: ${document.analysisModel || "Not generated"}`
    ].join("\n"),
    { x: MARGIN_X, y: 3.05, w: 7.2, h: 1.2, fontSize: 14, color: MUTED, breakLine: false, fit: "shrink" }
  );
  slide.addText("Generated by DocuMuse", { x: MARGIN_X, y: 6.35, w: 4, h: 0.35, fontSize: 13, color: BLUE, bold: true });
}

function addSummarySlide(pptx: PptxDocument, document: ParsedDocument) {
  const slide = newSlide(pptx);
  addTitle(slide, "Summary");
  const analysis = document.analysis;
  const empty = document.analysisStatus !== "completed";
  addLabel(slide, "One-sentence summary", 1.28);
  addBodyText(slide, empty ? "尚未生成分析结果" : analysis?.oneSentenceSummary || "尚未生成分析结果", 1.66, 1.0, 220);
  addLabel(slide, "Full summary", 3.0);
  addBodyText(slide, empty ? "尚未生成分析结果" : analysis?.summary || "尚未生成分析结果", 3.38, 2.25, 520);
}

function addKeyPointsSlide(pptx: PptxDocument, document: ParsedDocument) {
  const slide = newSlide(pptx);
  addTitle(slide, "Key Points");
  addBullets(slide, (document.analysis?.keyPoints ?? []).slice(0, 6), 1.35, 5.3, "尚未生成分析结果");
}

function addKeywordsSlide(pptx: PptxDocument, document: ParsedDocument) {
  const slide = newSlide(pptx);
  addTitle(slide, "Keywords");
  const keywords = (document.analysis?.keywords ?? []).slice(0, 20);
  if (!keywords.length) {
    addBodyText(slide, "尚未生成分析结果", 1.35, 1.2, 120);
    return;
  }

  keywords.forEach((keyword, index) => {
    const col = index % 4;
    const row = Math.floor(index / 4);
    slide.addText(truncateText(keyword, 24), {
      x: MARGIN_X + col * 3.05,
      y: 1.35 + row * 0.72,
      w: 2.6,
      h: 0.42,
      fontSize: 13,
      bold: true,
      color: BLUE,
      align: "center",
      margin: 0.06,
      fill: { color: LIGHT_BLUE },
      line: { color: "BFDBFE", width: 1 },
      fit: "shrink"
    });
  });
}

function addSectionSlides(pptx: PptxDocument, document: ParsedDocument) {
  const sections = document.analysis?.sectionSummaries ?? [];
  if (!sections.length) {
    const slide = newSlide(pptx);
    addTitle(slide, "Section Analysis");
    addBodyText(slide, "尚未生成分析结果", 1.35, 1.2, 120);
    return;
  }

  for (let index = 0; index < sections.length; index += 2) {
    const slide = newSlide(pptx);
    addTitle(slide, `Section Analysis ${Math.floor(index / 2) + 1}`);
    sections.slice(index, index + 2).forEach((section, localIndex) => {
      const y = 1.22 + localIndex * 2.75;
      slide.addText(truncateText(section.title || `Section ${index + localIndex + 1}`, 80), { x: MARGIN_X, y, w: 11.5, h: 0.34, fontSize: 16, bold: true, color: DARK, fit: "shrink" });
      slide.addText(truncateText(section.summary || "尚未生成分析结果", 210), { x: MARGIN_X, y: y + 0.48, w: 11.4, h: 0.62, fontSize: 11, color: MUTED, breakLine: false, fit: "shrink" });
      addBullets(slide, (section.keyPoints ?? []).slice(0, 3), y + 1.18, 1.15, "尚未生成核心观点", 10.5);
    });
  }
}

function addPptOutlineSlides(pptx: PptxDocument, document: ParsedDocument) {
  const outline = document.analysis?.pptOutline ?? [];
  if (!outline.length) {
    const slide = newSlide(pptx);
    addTitle(slide, "PPT Outline");
    addBodyText(slide, "尚未生成 PPT 大纲", 1.35, 1.2, 140);
    return;
  }

  for (let index = 0; index < outline.length; index += 3) {
    const slide = newSlide(pptx);
    addTitle(slide, `PPT Outline ${Math.floor(index / 3) + 1}`);
    outline.slice(index, index + 3).forEach((item, localIndex) => {
      const y = 1.18 + localIndex * 1.8;
      slide.addText(`Slide ${index + localIndex + 1}: ${truncateText(item.title || "Untitled", 70)}`, { x: MARGIN_X, y, w: 11.4, h: 0.32, fontSize: 14, bold: true, color: DARK, fit: "shrink" });
      addBullets(slide, (item.bullets ?? []).slice(0, 3), y + 0.42, 1.05, "尚未生成要点", 10.5);
    });
  }
}

function addCreativeSlide(pptx: PptxDocument, document: ParsedDocument) {
  const slide = newSlide(pptx);
  addTitle(slide, "Creative Outputs");
  addLabel(slide, "Podcast script excerpt", 1.25);
  addBodyText(slide, document.analysis?.podcastScript || "尚未生成播客脚本", 1.62, 1.45, 360);

  addLabel(slide, "Image prompts", 3.75);
  const prompts = document.analysis?.imagePrompts ?? [];
  if (!prompts.length) {
    addBodyText(slide, "尚未生成图片提示词", 4.12, 0.8, 120);
    return;
  }

  prompts.slice(0, 3).forEach((item, index) => {
    const y = 4.12 + index * 0.75;
    slide.addText(truncateText(item.title || `Prompt ${index + 1}`, 50), { x: MARGIN_X, y, w: 3.1, h: 0.25, fontSize: 11, bold: true, color: DARK, fit: "shrink" });
    slide.addText(truncateText(item.prompt || "", 140), { x: 3.6, y, w: 8.3, h: 0.42, fontSize: 10, color: MUTED, fit: "shrink" });
  });
}

function addChatSlides(pptx: PptxDocument, document: ParsedDocument) {
  const rounds = recentChatRounds(document.chatMessages ?? [], 5);
  if (!rounds.length) {
    const slide = newSlide(pptx);
    addTitle(slide, "Document Q&A");
    addBodyText(slide, "暂无问答记录", 1.35, 1.2, 120);
    return;
  }

  for (let index = 0; index < rounds.length; index += 2) {
    const slide = newSlide(pptx);
    addTitle(slide, `Document Q&A ${Math.floor(index / 2) + 1}`);
    rounds.slice(index, index + 2).forEach((round, localIndex) => {
      const y = 1.12 + localIndex * 2.9;
      slide.addText(`Q: ${truncateText(round.question, 120)}`, { x: MARGIN_X, y, w: 11.4, h: 0.36, fontSize: 12, bold: true, color: DARK, fit: "shrink" });
      slide.addText(`A: ${truncateText(stripMarkdown(round.answer), 260)}`, { x: MARGIN_X, y: y + 0.46, w: 11.4, h: 0.8, fontSize: 10.5, color: MUTED, fit: "shrink" });
      const sourceText = round.sources.length
        ? round.sources.slice(0, 2).map((source) => `${source.sourceHint}: ${truncateText(source.quote, 80)}`).join("\n")
        : "未找到明确来源";
      slide.addText(sourceText, { x: MARGIN_X, y: y + 1.36, w: 11.4, h: 0.7, fontSize: 9.5, color: BLUE, fit: "shrink" });
    });
  }
}

function addClosingSlide(pptx: PptxDocument) {
  const slide = newSlide(pptx);
  slide.addText("Generated by DocuMuse", { x: 2.2, y: 2.8, w: 9, h: 0.8, fontSize: 34, bold: true, color: BLUE, align: "center" });
  slide.addText("Local AI document reading workspace", { x: 3.3, y: 3.75, w: 6.8, h: 0.35, fontSize: 14, color: MUTED, align: "center" });
}

function newSlide(pptx: PptxDocument) {
  const slide = pptx.addSlide();
  slide.background = { color: "FFFFFF" };
  slide.addText("DocuMuse", { x: 11.1, y: 6.95, w: 1.55, h: 0.2, fontSize: 8.5, color: "94A3B8", align: "right" });
  return slide;
}

function addTitle(slide: PptxSlide, text: string) {
  slide.addText(text, { x: MARGIN_X, y: 0.42, w: 11.6, h: 0.52, fontSize: 24, bold: true, color: BLUE, fit: "shrink" });
}

function addLabel(slide: PptxSlide, text: string, y: number) {
  slide.addText(text, { x: MARGIN_X, y, w: 8, h: 0.25, fontSize: 11, bold: true, color: BLUE, fit: "shrink" });
}

function addBodyText(slide: PptxSlide, text: string, y: number, h: number, maxLength: number) {
  slide.addText(truncateText(text, maxLength), {
    x: MARGIN_X,
    y,
    w: SLIDE_W - MARGIN_X * 2,
    h,
    fontSize: 13,
    color: DARK,
    breakLine: false,
    fit: "shrink",
    margin: 0.08,
    fill: { color: LIGHT_GRAY },
    line: { color: "E2E8F0", width: 1 }
  });
}

function addBullets(slide: PptxSlide, bullets: string[], y: number, h: number, emptyText = "尚未生成分析结果", width = 11.2) {
  const items = bullets.filter(Boolean).slice(0, 6);
  if (!items.length) {
    slide.addText(emptyText, { x: MARGIN_X, y, w: width, h: 0.4, fontSize: 12, color: MUTED, fit: "shrink" });
    return;
  }

  slide.addText(
    items.map((item) => ({ text: truncateText(item, 150), options: { bullet: { indent: 12 }, hanging: 4, breakLine: true } })),
    { x: MARGIN_X, y, w: width, h, fontSize: 12, color: DARK, fit: "shrink", breakLine: false }
  );
}

function recentChatRounds(messages: DocumentChatMessage[], limit: number) {
  const rounds: Array<{ question: string; answer: string; sources: NonNullable<DocumentChatMessage["sources"]> }> = [];
  let pendingQuestion = "";

  for (const message of messages) {
    if (message.role === "user") {
      pendingQuestion = message.content;
    } else if (message.role === "assistant" && pendingQuestion) {
      rounds.push({
        question: pendingQuestion,
        answer: message.content,
        sources: message.sources ?? []
      });
      pendingQuestion = "";
    }
  }

  return rounds.slice(-limit);
}

export function truncateText(value: unknown, maxLength: number) {
  const text = safeText(value).replace(/\s+/g, " ").trim();
  if (text.length <= maxLength) return text;
  return `${text.slice(0, Math.max(0, maxLength - 1)).trimEnd()}...`;
}

function stripMarkdown(value: string) {
  return value
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/^>\s?/gm, "")
    .replace(/^\s*[-*]\s+/gm, "")
    .trim();
}

function safeText(value: unknown) {
  return typeof value === "string" ? value : "";
}
