import pptxgen from "pptxgenjs";
import type { DocumentChatMessage, ParsedDocument } from "../documentTypes";

const THEME = {
  blue: "2563EB",
  dark: "111827",
  gray: "64748B",
  lightGray: "F1F5F9",
  border: "E2E8F0",
  paleBlue: "EFF6FF",
  white: "FFFFFF"
};

const SLIDE = {
  width: 13.333,
  height: 7.5,
  marginX: 0.62,
  titleY: 0.36,
  footerY: 7.08
};

const EMPTY_ANALYSIS = "尚未生成分析结果";
const EMPTY_CHAT = "暂无问答记录";
const EMPTY_OUTLINE = "尚未生成 PPT 大纲";
const EMPTY_GENERATED = "尚未生成";

type PptxDocument = InstanceType<typeof pptxgen>;
type PptxSlide = ReturnType<PptxDocument["addSlide"]>;

type CardOptions = {
  x: number;
  y: number;
  w: number;
  h: number;
  title?: string;
  body?: string;
  fill?: string;
  accent?: boolean;
  bodyMax?: number;
  titleSize?: number;
  bodySize?: number;
};

export async function buildDocumentPptxExport(document: ParsedDocument): Promise<Buffer> {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "DocuMuse";
  pptx.company = "DocuMuse";
  pptx.subject = "DocuMuse document analysis export";
  pptx.title = cleanText(document.title || document.filename || "DocuMuse Export");
  pptx.theme = {
    headFontFace: "Arial",
    bodyFontFace: "Arial"
  };

  let page = 1;
  addCoverSlide(pptx, document);
  addSummarySlide(pptx, document, page++);
  addKeyPointsSlide(pptx, document, page++);
  addKeywordsSlide(pptx, document, page++);
  page = addSectionSlides(pptx, document, page);
  page = addPptOutlineSlides(pptx, document, page);
  addPodcastSlide(pptx, document, page++);
  page = addImagePromptSlides(pptx, document, page);
  page = addChatSlides(pptx, document, page);
  addClosingSlide(pptx, page++);

  const output = await pptx.write({ outputType: "nodebuffer", compression: true });
  return Buffer.isBuffer(output) ? output : Buffer.from(output as ArrayBuffer);
}

function addCoverSlide(pptx: PptxDocument, document: ParsedDocument) {
  const slide = newBaseSlide(pptx);
  slide.addShape(pptx.ShapeType.rect, { x: 9.6, y: 0, w: 3.75, h: 7.5, fill: { color: THEME.paleBlue }, line: { color: THEME.paleBlue } });
  slide.addShape(pptx.ShapeType.rect, { x: 10.25, y: 0.72, w: 2.2, h: 5.9, fill: { color: "DBEAFE", transparency: 35 }, line: { color: "DBEAFE", transparency: 100 } });
  slide.addText("DocuMuse", { x: SLIDE.marginX, y: 0.55, w: 2.8, h: 0.35, fontSize: 16, bold: true, color: THEME.blue });
  slide.addText(truncateText(document.title || document.filename, 120), {
    x: SLIDE.marginX,
    y: 1.65,
    w: 8.5,
    h: 1.35,
    fontSize: 34,
    bold: true,
    color: THEME.dark,
    fit: "shrink",
    breakLine: false
  });
  slide.addText("AI Document Reading Report", { x: SLIDE.marginX, y: 3.12, w: 5.6, h: 0.35, fontSize: 16, color: THEME.gray });
  addCard(slide, {
    x: SLIDE.marginX,
    y: 4.05,
    w: 6.75,
    h: 1.7,
    title: "Export metadata",
    body: [
      `File: ${document.filename}`,
      `Provider: ${document.analysisProvider || "Not generated"}`,
      `Model: ${document.analysisModel || "Not generated"}`,
      `Exported at: ${new Date().toLocaleString("zh-CN")}`
    ].join("\n"),
    bodyMax: 260
  });
  slide.addText("Generated by DocuMuse", { x: SLIDE.marginX, y: 6.62, w: 4.8, h: 0.3, fontSize: 13, bold: true, color: THEME.blue });
}

function addSummarySlide(pptx: PptxDocument, document: ParsedDocument, page: number) {
  const slide = newContentSlide(pptx, "Summary", "A concise reading report generated from the existing document analysis.", page);
  const hasAnalysis = document.analysisStatus === "completed";
  addCard(slide, {
    x: SLIDE.marginX,
    y: 1.25,
    w: 12.05,
    h: 1.55,
    title: "One-sentence summary",
    body: hasAnalysis ? document.analysis?.oneSentenceSummary || EMPTY_ANALYSIS : EMPTY_ANALYSIS,
    fill: THEME.paleBlue,
    accent: true,
    bodySize: 17,
    bodyMax: 220
  });
  addCard(slide, {
    x: SLIDE.marginX,
    y: 3.15,
    w: 12.05,
    h: 2.85,
    title: "Full summary",
    body: hasAnalysis ? document.analysis?.summary || EMPTY_ANALYSIS : EMPTY_ANALYSIS,
    bodySize: 14,
    bodyMax: 640
  });
}

function addKeyPointsSlide(pptx: PptxDocument, document: ParsedDocument, page: number) {
  const slide = newContentSlide(pptx, "Key Points", "Top takeaways from the document.", page);
  const points = (document.analysis?.keyPoints ?? []).slice(0, 6);
  if (!points.length) {
    addCard(slide, { x: SLIDE.marginX, y: 1.45, w: 12.05, h: 1.4, body: EMPTY_ANALYSIS, bodySize: 16 });
    return;
  }

  points.forEach((point, index) => {
    const col = index % 2;
    const row = Math.floor(index / 2);
    const x = SLIDE.marginX + col * 6.18;
    const y = 1.28 + row * 1.78;
    addCard(slide, {
      x,
      y,
      w: 5.82,
      h: 1.34,
      title: String(index + 1).padStart(2, "0"),
      body: point,
      fill: index % 2 === 0 ? THEME.paleBlue : THEME.lightGray,
      accent: index % 2 === 0,
      bodySize: 13,
      bodyMax: 135
    });
  });
}

function addKeywordsSlide(pptx: PptxDocument, document: ParsedDocument, page: number) {
  const slide = newContentSlide(pptx, "Keywords", "Core concepts extracted from the analysis.", page);
  const keywords = (document.analysis?.keywords ?? []).slice(0, 20);
  if (!keywords.length) {
    addCard(slide, { x: SLIDE.marginX, y: 1.45, w: 12.05, h: 1.4, body: EMPTY_ANALYSIS, bodySize: 16 });
    return;
  }
  addTagList(slide, keywords, { x: SLIDE.marginX, y: 1.35, w: 12.05, h: 4.9 });
}

function addSectionSlides(pptx: PptxDocument, document: ParsedDocument, startPage: number) {
  const sections = document.analysis?.sectionSummaries ?? [];
  if (!sections.length) {
    const slide = newContentSlide(pptx, "Section Analysis", "Section-level summaries and key points.", startPage);
    addCard(slide, { x: SLIDE.marginX, y: 1.45, w: 12.05, h: 1.4, body: EMPTY_ANALYSIS, bodySize: 16 });
    return startPage + 1;
  }

  let page = startPage;
  splitIntoSlides(sections, 2).forEach((group, groupIndex) => {
    const slide = newContentSlide(pptx, `Section Analysis ${groupIndex + 1}`, "One or two sections per page for readability.", page++);
    group.forEach((section, index) => {
      const y = 1.25 + index * 2.82;
      addCard(slide, {
        x: SLIDE.marginX,
        y,
        w: 12.05,
        h: 2.28,
        title: section.title || `Section ${groupIndex * 2 + index + 1}`,
        body: [truncateText(section.summary || EMPTY_ANALYSIS, 245), ...formatInlineBullets((section.keyPoints ?? []).slice(0, 3), 95)].join("\n"),
        bodySize: 11.5,
        bodyMax: 520
      });
    });
  });
  return page;
}

function addPptOutlineSlides(pptx: PptxDocument, document: ParsedDocument, startPage: number) {
  const outline = document.analysis?.pptOutline ?? [];
  if (!outline.length) {
    const slide = newContentSlide(pptx, "PPT Outline", "Generated outline from the existing document analysis.", startPage);
    addCard(slide, { x: SLIDE.marginX, y: 1.45, w: 12.05, h: 1.4, body: EMPTY_OUTLINE, bodySize: 16 });
    return startPage + 1;
  }

  let page = startPage;
  splitIntoSlides(outline, 3).forEach((group, groupIndex) => {
    const slide = newContentSlide(pptx, `PPT Outline ${groupIndex + 1}`, "Slide cards based on the generated outline.", page++);
    group.forEach((item, index) => {
      addCard(slide, {
        x: SLIDE.marginX,
        y: 1.2 + index * 1.82,
        w: 12.05,
        h: 1.38,
        title: `Slide ${groupIndex * 3 + index + 1}: ${truncateText(item.title || "Untitled", 72)}`,
        body: formatInlineBullets((item.bullets ?? []).slice(0, 3), 90).join("\n") || EMPTY_GENERATED,
        bodySize: 11.5,
        bodyMax: 360
      });
    });
  });
  return page;
}

function addPodcastSlide(pptx: PptxDocument, document: ParsedDocument, page: number) {
  const slide = newContentSlide(pptx, "Podcast Script", "Short excerpt only. No audio is generated.", page);
  addCard(slide, {
    x: SLIDE.marginX,
    y: 1.25,
    w: 12.05,
    h: 4.75,
    title: "Script excerpt",
    body: document.analysis?.podcastScript || EMPTY_GENERATED,
    bodySize: 13.2,
    bodyMax: 800
  });
}

function addImagePromptSlides(pptx: PptxDocument, document: ParsedDocument, startPage: number) {
  const prompts = document.analysis?.imagePrompts ?? [];
  if (!prompts.length) {
    const slide = newContentSlide(pptx, "Image Prompts", "Text prompts only. No images are generated.", startPage);
    addCard(slide, { x: SLIDE.marginX, y: 1.45, w: 12.05, h: 1.4, body: EMPTY_GENERATED, bodySize: 16 });
    return startPage + 1;
  }

  let page = startPage;
  splitIntoSlides(prompts, 3).forEach((group, groupIndex) => {
    const slide = newContentSlide(pptx, `Image Prompts ${groupIndex + 1}`, "Text prompts only. No images are generated.", page++);
    group.forEach((item, index) => {
      addCard(slide, {
        x: SLIDE.marginX,
        y: 1.2 + index * 1.82,
        w: 12.05,
        h: 1.38,
        title: item.title || `Prompt ${groupIndex * 3 + index + 1}`,
        body: item.prompt || EMPTY_GENERATED,
        bodySize: 11.5,
        bodyMax: 220
      });
    });
  });
  return page;
}

function addChatSlides(pptx: PptxDocument, document: ParsedDocument, startPage: number) {
  const rounds = recentChatRounds(document.chatMessages ?? [], 5);
  if (!rounds.length) {
    const slide = newContentSlide(pptx, "Document Q&A", "Recent grounded question-answer records.", startPage);
    addCard(slide, { x: SLIDE.marginX, y: 1.45, w: 12.05, h: 1.4, body: EMPTY_CHAT, bodySize: 16 });
    return startPage + 1;
  }

  let page = startPage;
  splitIntoSlides(rounds, 2).forEach((group, groupIndex) => {
    const slide = newContentSlide(pptx, `Document Q&A ${groupIndex + 1}`, "Recent question-answer rounds with short source hints.", page++);
    group.forEach((round, index) => {
      const sourceText = round.sources.length
        ? round.sources.slice(0, 2).map((source) => `Source: ${source.sourceHint} — ${truncateText(source.quote, 95)}`).join("\n")
        : "Source: 未找到明确来源";
      addCard(slide, {
        x: SLIDE.marginX,
        y: 1.18 + index * 2.78,
        w: 12.05,
        h: 2.22,
        title: `Q: ${truncateText(round.question, 110)}`,
        body: [`A: ${truncateText(stripMarkdown(round.answer), 235)}`, sourceText].join("\n"),
        bodySize: 10.8,
        bodyMax: 520
      });
    });
  });
  return page;
}

function addClosingSlide(pptx: PptxDocument, page: number) {
  const slide = newBaseSlide(pptx);
  slide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: SLIDE.width, h: SLIDE.height, fill: { color: THEME.paleBlue }, line: { color: THEME.paleBlue } });
  slide.addText("Generated by DocuMuse", { x: 2.05, y: 2.55, w: 9.3, h: 0.7, fontSize: 34, bold: true, color: THEME.blue, align: "center" });
  slide.addText("AI Document Reading Workspace", { x: 3.0, y: 3.38, w: 7.4, h: 0.38, fontSize: 15, color: THEME.gray, align: "center" });
  slide.addText(`Exported at ${new Date().toLocaleString("zh-CN")}`, { x: 3.0, y: 4.02, w: 7.4, h: 0.28, fontSize: 11, color: THEME.gray, align: "center" });
  addFooter(slide, page);
}

function newBaseSlide(pptx: PptxDocument) {
  const slide = pptx.addSlide();
  slide.background = { color: THEME.white };
  return slide;
}

function newContentSlide(pptx: PptxDocument, title: string, subtitle: string, page: number) {
  const slide = newBaseSlide(pptx);
  addSlideTitle(slide, title, subtitle);
  addFooter(slide, page);
  return slide;
}

function addSlideTitle(slide: PptxSlide, title: string, subtitle?: string) {
  slide.addText(title, { x: SLIDE.marginX, y: SLIDE.titleY, w: 8.8, h: 0.45, fontSize: 22, bold: true, color: THEME.blue, fit: "shrink" });
  if (subtitle) {
    slide.addText(subtitle, { x: SLIDE.marginX, y: 0.84, w: 9.8, h: 0.25, fontSize: 10.5, color: THEME.gray, fit: "shrink" });
  }
  slide.addShape("line", { x: SLIDE.marginX, y: 1.06, w: 12.05, h: 0, line: { color: THEME.border, width: 1 } });
}

function addFooter(slide: PptxSlide, page?: number) {
  slide.addShape("line", { x: SLIDE.marginX, y: SLIDE.footerY - 0.08, w: 12.05, h: 0, line: { color: THEME.border, width: 0.8 } });
  slide.addText("DocuMuse", { x: SLIDE.marginX, y: SLIDE.footerY, w: 2.1, h: 0.18, fontSize: 8.5, bold: true, color: THEME.gray });
  if (page) {
    slide.addText(String(page).padStart(2, "0"), { x: 12.0, y: SLIDE.footerY, w: 0.75, h: 0.18, fontSize: 8.5, color: THEME.gray, align: "right" });
  }
}

function addCard(slide: PptxSlide, options: CardOptions) {
  slide.addShape("roundRect", {
    x: options.x,
    y: options.y,
    w: options.w,
    h: options.h,
    rectRadius: 0.08,
    fill: { color: options.fill || THEME.lightGray },
    line: { color: options.accent ? "BFDBFE" : THEME.border, width: 1 }
  });

  const textX = options.x + 0.24;
  let bodyY = options.y + 0.22;
  if (options.title) {
    slide.addText(truncateText(options.title, 95), {
      x: textX,
      y: options.y + 0.18,
      w: options.w - 0.48,
      h: 0.28,
      fontSize: options.titleSize || 12.5,
      bold: true,
      color: options.accent ? THEME.blue : THEME.dark,
      fit: "shrink"
    });
    bodyY = options.y + 0.58;
  }

  slide.addText(truncateText(options.body || EMPTY_GENERATED, options.bodyMax || 260), {
    x: textX,
    y: bodyY,
    w: options.w - 0.48,
    h: Math.max(0.2, options.y + options.h - bodyY - 0.18),
    fontSize: options.bodySize || 11.5,
    color: THEME.dark,
    breakLine: false,
    fit: "shrink",
    margin: 0.02
  });
}

function addTagList(slide: PptxSlide, tags: string[], bounds: { x: number; y: number; w: number; h: number }) {
  let x = bounds.x;
  let y = bounds.y;
  tags.forEach((tag) => {
    const label = truncateText(tag, 22);
    const width = Math.min(2.5, Math.max(1.05, 0.34 + label.length * 0.12));
    if (x + width > bounds.x + bounds.w) {
      x = bounds.x;
      y += 0.58;
    }
    if (y + 0.4 > bounds.y + bounds.h) return;
    slide.addText(label, {
      x,
      y,
      w: width,
      h: 0.38,
      fontSize: 12.2,
      bold: true,
      color: THEME.blue,
      align: "center",
      margin: 0.04,
      fill: { color: THEME.paleBlue },
      line: { color: "BFDBFE", width: 1 },
      fit: "shrink"
    });
    x += width + 0.18;
  });
}

function splitIntoSlides<T>(items: T[], itemsPerSlide: number) {
  const groups: T[][] = [];
  for (let index = 0; index < items.length; index += itemsPerSlide) {
    groups.push(items.slice(index, index + itemsPerSlide));
  }
  return groups;
}

function formatInlineBullets(items: string[], maxLength: number) {
  return items.filter(Boolean).slice(0, 4).map((item) => `• ${truncateText(item, maxLength)}`);
}

function recentChatRounds(messages: DocumentChatMessage[], limit: number) {
  const rounds: Array<{ question: string; answer: string; sources: NonNullable<DocumentChatMessage["sources"]> }> = [];
  let pendingQuestion = "";

  for (const message of messages) {
    if (message.role === "user") {
      pendingQuestion = message.content;
    } else if (message.role === "assistant" && pendingQuestion) {
      rounds.push({
        question: pendingQuestion,
        answer: message.content,
        sources: message.sources ?? []
      });
      pendingQuestion = "";
    }
  }

  return rounds.slice(-limit);
}

export function truncateText(value: unknown, maxLength: number) {
  const text = cleanText(value).replace(/\s+/g, " ").trim();
  if (!text) return "";
  if (text.length <= maxLength) return text;
  return `${text.slice(0, Math.max(0, maxLength - 1)).trimEnd()}…`;
}

function stripMarkdown(value: string) {
  return value
    .replace(/^#{1,6}\s+/gm, "")
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/`([^`]+)`/g, "$1")
    .replace(/^>\s?/gm, "")
    .replace(/^\s*[-*]\s+/gm, "")
    .trim();
}

function cleanText(value: unknown) {
  if (typeof value !== "string") return "";
  return value.replace(/\u0000/g, "").replace(/\r\n/g, "\n");
}
