import JSZip from "jszip";
import type { ParsedDocument } from "../documentTypes";
import { buildDocumentJsonExport } from "./jsonExporter";
import { buildDocumentMarkdownExport } from "./markdownExporter";
import { buildDocumentPptxExport } from "./pptxExporter";
import { buildPresetExportPlan, getExportPresetById } from "./exportPresets";
import type { ExportPresetId, PresetExportFile } from "./exportTypes";

export async function buildPresetZipExport(document: ParsedDocument, presetId: ExportPresetId): Promise<Buffer> {
  const preset = getExportPresetById(presetId);
  if (!preset) {
    throw new Error("Export preset does not exist.");
  }

  const plan = buildPresetExportPlan(presetId, document);
  const zip = new JSZip();
  const files: string[] = [];

  for (const file of plan.files) {
    const zipName = zipFilenameFor(file);
    files.push(zipName);

    if (file.format === "markdown") {
      zip.file(zipName, buildDocumentMarkdownExport(document));
    } else if (file.format === "chat-markdown") {
      zip.file(zipName, buildDocumentMarkdownExport(document, { only: "chat" }));
    } else if (file.format === "json") {
      zip.file(zipName, JSON.stringify(buildDocumentJsonExport(document), null, 2));
    } else if (file.format === "pptx") {
      zip.file(zipName, await buildDocumentPptxExport(document, pptxOptionsForPreset(presetId)));
    }
  }

  zip.file("README.txt", buildZipReadme({ presetLabel: preset.label, document, files }));
  const output = await zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
  return Buffer.isBuffer(output) ? output : Buffer.from(output);
}

function zipFilenameFor(file: PresetExportFile) {
  if (file.format === "markdown") return "documuse-report.md";
  if (file.format === "json") return "documuse-data.json";
  if (file.format === "pptx") return "documuse-slides.pptx";
  return "documuse-chat.md";
}

function pptxOptionsForPreset(presetId: ExportPresetId) {
  if (presetId === "presentation-pack") {
    return {
      theme: "blue" as const,
      cover: "report" as const,
      includeSummary: true,
      includeKeyPoints: true,
      includeKeywords: true,
      includeSections: true,
      includeOutline: true,
      includeCreative: false,
      includeChat: false
    };
  }
  return {
    theme: "blue" as const,
    cover: "report" as const,
    includeSummary: true,
    includeKeyPoints: true,
    includeKeywords: true,
    includeSections: true,
    includeOutline: true,
    includeCreative: true,
    includeChat: true
  };
}

function buildZipReadme({ presetLabel, document, files }: { presetLabel: string; document: ParsedDocument; files: string[] }) {
  return [
    "DocuMuse Export Preset Package",
    "",
    `Preset: ${presetLabel}`,
    `Document: ${document.title || document.filename}`,
    `Exported at: ${new Date().toLocaleString("zh-CN")}`,
    "",
    "Files:",
    ...files.map((file) => `- ${file}`),
    "- README.txt",
    "",
    "Generated by DocuMuse",
    "",
    "This package excludes secrets, internal model/debug data, full original document content, local settings, and absolute upload paths."
  ].join("\n");
}
